name: pyradio
summary: Command line internet radio player.
description: |
  Command line internet radio player.
  
  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.

base: core20
grade: stable
confinement: strict

website: https://github.com/coderholic/pyradio
contact: https://github.com/snapcrafters/pyradio/issues
issues: https://github.com/snapcrafters/pyradio/issues
source-code: https://github.com//snapcrafters/pyradio
license: MIT
version: '0.9.3.7'

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  pyradio:
    command: bin/pyradio
    plugs: [network, audio-playback, x11, network-bind]
    environment:
       LC_ALL: C.UTF-8
       LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba"

parts:
  pyradio:
    source: https://github.com/coderholic/pyradio.git
    plugin: python
    python-packages:
        - dnspython
        - psutil
        - requests
    stage-packages:
        - mplayer
        - libpulse0
        - samba-libs
        - libgpm2
        - libglu1-mesa
        - freeglut3
        - libslang2
