name: pyradio
summary: Command line internet radio player.
description: |
  Command line internet radio player.
  
  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.

base: core24
grade: stable
confinement: strict

website: https://github.com/coderholic/pyradio
contact: https://github.com/snapcrafters/pyradio/issues
issues: https://github.com/snapcrafters/pyradio/issues
source-code: https://github.com//snapcrafters/pyradio
license: MIT
version: '0.9.3.7'

apps:
  pyradio:
    command: bin/pyradio
    plugs:
        - audio-playback
        - network

parts:
  pyradio:
    plugin: python
    source: https://github.com/coderholic/pyradio.git
    python-requirements:
        - requirements_pipx.txt
